13 contact section 28.03.2023
Varbintech/next.varbintechcom pull request #35
Opened 2023-03-28 13:41 UTC by InnaLazarenko

2023-03-28 16:05 UTC, var-bin commented
@InnaLazarenko, we need to change `font-size` for the mobile view because of the issue

![18-58-10-6yp31](https://user-images.githubusercontent.com/3194163/228300462-b445037c-7d7b-4d58-bdad-7dbd571c48ca.jpg)

2023-03-28 18:51 UTC, InnaLazarenko commented on components/contact/Contact.tsx
> +                <LinkedInIcon sx={{ fontSize: '26px' }} />
'+

2023-03-28 18:51 UTC, InnaLazarenko commented on components/contact/Contact.tsx
> +              <ContactRedditLink
'+

2023-03-29 08:20 UTC, var-bin commented
@InnaLazarenko, it looks like we have some issues

![11-13-16-ycmx8](https://user-images.githubusercontent.com/3194163/228471827-f8163c80-084a-4fc0-8502-fa1ec07bec94.jpg)

2023-03-29 08:39 UTC, var-bin requested changes

2023-03-29 08:52 UTC, InnaLazarenko commented on components/contact/Contact.tsx
> +    <PageContainer id="services">
'+

2023-03-29 08:52 UTC, InnaLazarenko commented
> @InnaLazarenko, it looks like we have some issues
> 
> ![11-13-16-ycmx8](https://user-images.githubusercontent.com/3194163/228471827-f8163c80-084a-4fc0-8502-fa1ec07bec94.jpg)

+

2023-03-29 09:46 UTC, var-bin approved these changes

2023-03-29 09:47 UTC, merged